In [1001]:
# imports
import pandas as pd

##### importing data, cleaning, merging, etc. before creating visualization

In [1002]:
freedom_df = pd.read_csv('heritage-index-of-economic-freedom-2026-04-19_1352.csv', skiprows=4)
freedom_df = freedom_df.dropna(subset='Overall Score')
freedom_df

,Country,Index Year,Overall Score,Property Rights,Government Integrity,Judicial Effectiveness,Tax Burden,Government Spending,Fiscal Health,Business Freedom,Labor Freedom,Monetary Freedom,Trade Freedom,Investment Freedom,Financial Freedom
1,Albania,2024,64.8,56.8,36.6,50.0,88.8,69.8,51.7,74.1,51.5,75.7,82.6,70.0,70.0
2,Algeria,2024,43.9,27.5,27.7,28.9,79.4,54.7,13.8,54.4,51.4,71.9,57.4,30.0,30.0
3,Angola,2024,54.3,40.4,27.8,25.7,86.5,85.8,91.1,44.6,50.8,60.0,68.6,30.0,40.0
4,Argentina,2024,49.9,34.5,39.8,55.8,67.0,54.3,35.7,55.5,53.5,29.4,58.6,55.0,60.0
5,Armenia,2024,64.9,50.3,50.0,31.6,87.6,75.5,69.1,69.2,58.9,67.5,73.6,75.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Vanuatu,2024,62.2,63.3,47.9,71.0,98.8,45.0,90.4,55.1,40.1,69.9,59.6,65.0,40.0
179,Venezuela,2024,28.1,0.0,6.4,3.3,75.9,96.6,36.5,31.0,35.7,0.0,42.2,0.0,10.0
180,Vietnam,2024,62.8,49.6,38.7,35.4,80.4,87.9,94.6,73.9,54.6,69.3,79.8,40.0,50.0
182,Zambia,2024,48.4,36.2,30.0,44.1,74.1,71.7,0.6,49.0,40.4,66.2,63.4,55.0,50.0
183,Zimbabwe,2024,38.2,20.2,19.8,16.0,74.6,92.1,78.5,39.0,32.8,0.0,50.4,25.0,10.0

In [1003]:
opinion_df = pd.read_csv('AIopinions.csv')
opinion_df = opinion_df.dropna(how='all')

opinion_df

          Category    Country % of respondents
0   The job market     Global              31%
1           My job     Global              37%
2   The job market      China              44%
3           My job      China              62%
4   The job market  Indonesia              45%
..             ...        ...              ...
61          My job    Belgium              26%
62  The job market     Sweden              18%
63          My job     Sweden              32%
64  The job market     Canada              18%
65          My job     Canada              24%

[66 rows x 3 columns]

In [1004]:
x = opinion_df['Category'] == 'My job' # removes duplicates from the list

country_list = opinion_df.Country[x].tolist()

# after doing this once, the UK and Turkey were removed because they had different names in the different sets of data
    # im going to manually add the two names so they're not ommitted

country_list.append('United Kingdom')
country_list.append('Türkiye')

In [1005]:
# filtering freedom score data for only countries I want

freedom_df = freedom_df[freedom_df['Country'].isin(country_list)]
freedom_df.Country.size

32

In [1006]:
len(opinion_df[opinion_df['Category'] == 'My job'])

33

In [1007]:
freedom_df = freedom_df.reset_index()
freedom_df

,index,Country,Index Year,Overall Score,Property Rights,Government Integrity,Judicial Effectiveness,Tax Burden,Government Spending,Fiscal Health,Business Freedom,Labor Freedom,Monetary Freedom,Trade Freedom,Investment Freedom,Financial Freedom
0,4,Argentina,2024,49.9,34.5,39.8,55.8,67.0,54.3,35.7,55.5,53.5,29.4,58.6,55.0,60.0
1,6,Australia,2024,76.2,91.0,85.2,94.4,62.6,48.2,39.9,92.1,65.4,75.6,89.8,80.0,90.0
2,13,Belgium,2024,65.6,91.6,78.9,91.5,51.1,6.1,20.0,82.6,58.8,72.4,79.2,85.0,70.0
3,20,Brazil,2024,53.2,49.1,36.9,55.0,69.7,34.9,30.9,67.0,56.9,71.6,66.8,50.0,50.0
4,29,Canada,2024,72.4,88.6,73.1,95.0,75.8,34.7,33.9,84.1,69.5,70.3,83.6,80.0,80.0
5,32,Chile,2024,71.4,72.5,68.2,87.9,71.8,73.4,66.0,79.2,58.6,70.9,78.0,60.0,70.0
6,33,China,2024,48.5,46.9,41.6,39.5,69.1,65.7,8.1,68.1,57.8,71.8,73.6,20.0,20.0
7,34,Colombia,2024,59.2,45.0,38.1,58.3,68.7,65.3,19.5,68.8,61.9,72.3,72.6,70.0,70.0
8,57,France,2024,62.5,93.1,73.7,84.2,53.1,0.0,6.9,82.0,60.5,71.6,79.2,75.0,70.0
9,60,Germany,2024,72.1,95.3,86.0,93.0,59.3,24.1,71.9,84.2,53.7,68.8,79.2,80.0,70.0
10,69,Hungary,2024,61.2,69.6,44.3,63.0,85.4,27.7,11.5,73.5,62.0,68.8,79.2,80.0,70.0
11,71,India,2024,52.9,49.2,40.8,52.1,73.7,73.5,6.9,68.3,58.4,69.1,62.2,40.0,40.0
12,72,Indonesia,2024,63.5,39.2,38.6,44.5,81.7,90.2,66.8,73.1,59.5,78.4,79.6,50.0,60.0
13,75,Ireland,2024,82.6,93.5,83.4,94.3,78.0,82.4,91.7,91.3,62.8,74.5,79.2,90.0,70.0
14,77,Italy,2024,60.1,81.6,60.7,77.7,57.0,2.5,0.0,77.6,70.7,74.1,79.2,80.0,60.0
15,79,Japan,2024,67.5,94.6,82.6,93.6,63.3,42.5,0.0,77.5,68.6,81.7,75.8,70.0,60.0
16,98,Malaysia,2024,65.7,65.7,48.2,65.6,83.9,81.4,42.8,70.5,58.2,79.1,83.0,60.0,50.0
17,104,Mexico,2024,62.0,46.5,29.0,39.4,76.0,77.0,66.9,71.2,58.0,68.3,76.8,75.0,60.0
18,113,Netherlands,2024,77.3,95.6,87.8,96.2,53.1,37.1,88.1,88.6,60.5,71.5,79.2,90.0,80.0
19,114,New Zealand,2024,77.8,87.4,95.9,93.2,65.5,46.3,72.4,88.3,70.3,74.6,89.8,70.0,80.0
20,126,Peru,2024,64.8,44.9,36.3,48.2,79.1,81.8,67.8,69.5,59.3,74.0,81.4,75.0,60.0
21,127,Poland,2024,66.0,72.0,58.3,52.2,72.6,38.5,67.4,74.6,58.0,68.9,79.2,80.0,70.0
22,143,Singapore,2024,83.5,94.2,88.3,58.3,90.7,89.2,76.0,86.9,77.3,76.3,95.0,90.0,80.0
23,148,South Africa,2024,55.3,44.7,48.0,58.3,65.2,66.9,19.7,61.4,72.1,74.5,72.4,40.0,40.0
24,149,South Korea,2024,73.1,88.3,69.2,76.9,59.0,78.9,91.6,85.0,57.2,77.3,73.4,60.0,60.0
25,150,Spain,2024,63.3,87.2,64.0,73.6,57.0,26.0,0.0,79.7,63.6,74.1,84.2,80.0,70.0
26,154,Sweden,2024,77.5,96.2,93.2,95.4,50.6,28.5,97.1,84.9,65.9,74.4,79.2,85.0,80.0
27,155,Switzerland,2024,83.0,94.2,91.3,98.1,70.4,64.6,95.7,89.3,60.7,80.8,86.4,85.0,80.0
28,160,Thailand,2024,59.0,45.0,38.1,35.2,81.1,80.3,46.8,70.3,56.3,66.7,72.8,55.0,60.0
29,169,Türkiye,2024,56.2,40.6,35.0,24.4,72.5,71.0,77.5,59.2,54.6,38.5,70.8,70.0,60.0
30,174,United Kingdom,2024,68.6,94.6,84.1,84.3,62.3,34.3,0.0,82.7,63.2,73.6,83.6,80.0,80.0
31,175,United States,2024,70.1,95.1,76.4,74.8,74.8,48.7,0.0,84.8,77.7,73.8,75.6,80.0,80.0

In [1008]:
# now I just need to create a global average economic freedom score, then i'll have 33 rows to merge to the other 33 rows by their name

avg_freedom = freedom_df['Overall Score'].mean()
avg_freedom.round(1)

np.float64(66.3)

In [1009]:
freedom_df.loc[32] = {
    'Country': 'Global',
    'Index Year': 2024,
    'Overall Score': avg_freedom.round(1)
}

In [1010]:
freedom_df = freedom_df[['Country' , 'Overall Score']]
freedom_df

           Country  Overall Score
0        Argentina           49.9
1        Australia           76.2
2          Belgium           65.6
3           Brazil           53.2
4           Canada           72.4
5            Chile           71.4
6            China           48.5
7         Colombia           59.2
8           France           62.5
9          Germany           72.1
10         Hungary           61.2
11           India           52.9
12       Indonesia           63.5
13         Ireland           82.6
14           Italy           60.1
15           Japan           67.5
16        Malaysia           65.7
17          Mexico           62.0
18     Netherlands           77.3
19     New Zealand           77.8
20            Peru           64.8
21          Poland           66.0
22       Singapore           83.5
23    South Africa           55.3
24     South Korea           73.1
25           Spain           63.3
26          Sweden           77.5
27     Switzerland           83.0
28        Thailand           59.0
29         Türkiye           56.2
30  United Kingdom           68.6
31   United States           70.1
32          Global           66.3

In [1011]:
freedom_df['Country'].replace('Türkiye' , 'Turkey' , inplace= True)
opinion_df['Country'].replace('Great Britain' , 'United Kingdom' , inplace= True) # I know they aren't the same, 
                                                                    # but the freedom score applies to the UK, as the UK is a subset of Great Britain

freedom_df

C:\Users\Brennen\AppData\Local\Temp\ipykernel_1660\3421722902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  freedom_df['Country'].replace('Türkiye' , 'Turkey' , inplace= True)

           Country  Overall Score
0        Argentina           49.9
1        Australia           76.2
2          Belgium           65.6
3           Brazil           53.2
4           Canada           72.4
5            Chile           71.4
6            China           48.5
7         Colombia           59.2
8           France           62.5
9          Germany           72.1
10         Hungary           61.2
11           India           52.9
12       Indonesia           63.5
13         Ireland           82.6
14           Italy           60.1
15           Japan           67.5
16        Malaysia           65.7
17          Mexico           62.0
18     Netherlands           77.3
19     New Zealand           77.8
20            Peru           64.8
21          Poland           66.0
22       Singapore           83.5
23    South Africa           55.3
24     South Korea           73.1
25           Spain           63.3
26          Sweden           77.5
27     Switzerland           83.0
28        Thailand           59.0
29          Turkey           56.2
30  United Kingdom           68.6
31   United States           70.1
32          Global           66.3

In [1012]:
# now I can merge

all_data = pd.merge(opinion_df , freedom_df , on = 'Country' , how='left')
all_data.rename(columns = {
    '% of respondents' : '% expecting improvement' , 
    'Overall Score' : 'Freedom Score', 
} , inplace = True)

all_data

          Category    Country % expecting improvement  Freedom Score
0   The job market     Global                     31%           66.3
1           My job     Global                     37%           66.3
2   The job market      China                     44%           48.5
3           My job      China                     62%           48.5
4   The job market  Indonesia                     45%           63.5
..             ...        ...                     ...            ...
61          My job    Belgium                     26%           65.6
62  The job market     Sweden                     18%           77.5
63          My job     Sweden                     32%           77.5
64  The job market     Canada                     18%           72.4
65          My job     Canada                     24%           72.4

[66 rows x 4 columns]

In [1013]:
all_data["% expecting improvement"] = all_data["% expecting improvement"].str.replace("%","").astype(int)
all_data

          Category    Country  % expecting improvement  Freedom Score
0   The job market     Global                       31           66.3
1           My job     Global                       37           66.3
2   The job market      China                       44           48.5
3           My job      China                       62           48.5
4   The job market  Indonesia                       45           63.5
..             ...        ...                      ...            ...
61          My job    Belgium                       26           65.6
62  The job market     Sweden                       18           77.5
63          My job     Sweden                       32           77.5
64  The job market     Canada                       18           72.4
65          My job     Canada                       24           72.4

[66 rows x 4 columns]

In [1014]:
all_data['Freedom Score'].describe() # so I know the range to bin my values

count    66.000000
mean     66.312121
std       9.384890
min      48.500000
25%      60.100000
50%      65.700000
75%      72.400000
max      83.500000
Name: Freedom Score, dtype: float64

In [1015]:
def binning(value):
    if pd.isna(value):
        raise ValueError("Freedom Score is missing, this should not happen")
    if value < 45:
        raise ValueError("Freedom Score is below 45, this should not happen (data min is 48.5)")
    elif value < 55:
        return "Low (45-55)"
    elif value < 65:
        return "Mid-low (55-65)"
    elif value < 75:
        return "Mid-high (65-75)"
    elif value < 85:
        return "High (75-85)"
    else: # >= 85
        raise ValueError("Freedom Score is 85 or higher, this should not happen (data max is 83.5)")


all_data['Freedom Score'] = all_data['Freedom Score'].apply(binning)
all_data

          Category    Country  % expecting improvement     Freedom Score
0   The job market     Global                       31  Mid-high (65-75)
1           My job     Global                       37  Mid-high (65-75)
2   The job market      China                       44       Low (45-55)
3           My job      China                       62       Low (45-55)
4   The job market  Indonesia                       45   Mid-low (55-65)
..             ...        ...                      ...               ...
61          My job    Belgium                       26  Mid-high (65-75)
62  The job market     Sweden                       18      High (75-85)
63          My job     Sweden                       32      High (75-85)
64  The job market     Canada                       18  Mid-high (65-75)
65          My job     Canada                       24  Mid-high (65-75)

[66 rows x 4 columns]

##### creating visualization

In [1016]:
# imports
import plotly.express as px

In [1017]:
# pivot table
df_plot = all_data.pivot(
    index=['Country', 'Freedom Score'],
    columns='Category',
    values='% expecting improvement'
).reset_index()

# rename to Economic Freedom Score everywhere
df_plot = df_plot.rename(columns={'Freedom Score': 'Economic Freedom Score'})
df_plot['OriginalBin'] = df_plot['Economic Freedom Score']

bin_list = ['All', 'Low (45-55)', 'Mid-low (55-65)', 'Mid-high (65-75)', 'High (75-85)']

# "All" frame
all_df = df_plot.copy()
all_df['Economic Freedom Score'] = 'All'

df_animated = pd.concat([all_df, df_plot], ignore_index=True)

# Duplicate global into every frame
global_base = df_plot[df_plot['Country'] == 'Global'].copy()
extra_globals = []
for b in bin_list:
    already_present = df_animated[
        (df_animated['Country'] == 'Global') & (df_animated['Economic Freedom Score'] == b)
    ]
    if already_present.empty:
        g = global_base.copy()
        g['Economic Freedom Score'] = b
        extra_globals.append(g)

if extra_globals:
    df_animated = pd.concat([df_animated] + extra_globals, ignore_index=True)

# color by original bin
df_animated['LegendGroup'] = df_animated.apply(
    lambda row: 'Global' if row['Country'] == 'Global' else row['OriginalBin'],
    axis=1
)

# NaN placeholders so Plotly clears missing groups per frame
all_legend_groups = ['Low (45-55)', 'Mid-low (55-65)', 'Mid-high (65-75)', 'High (75-85)', 'Global']
placeholder_rows = []
for b in bin_list:
    for lg in all_legend_groups:
        has_data = df_animated[
            (df_animated['Economic Freedom Score'] == b) &
            (df_animated['LegendGroup'] == lg)
        ]
        if has_data.empty:
            placeholder_rows.append({
                'Country': '__placeholder__',
                'Economic Freedom Score': b,
                'OriginalBin': lg,
                'LegendGroup': lg,
                'The job market': float('nan'),
                'My job': float('nan')
            })

if placeholder_rows:
    df_animated = pd.concat([df_animated, pd.DataFrame(placeholder_rows)], ignore_index=True)

# Custom group colors
color_discrete_map = {
    'Low (45-55)':      "#E07A5F",
    'Mid-low (55-65)':  "#F2CC8F",
    'Mid-high (65-75)': '#8DA9C4',
    'High (75-85)':     "#3D5A80",
    'Global':           'black'
}

# create figure
fig = px.scatter(
    df_animated,
    x='The job market',
    y='My job',
    color='LegendGroup',
    color_discrete_map=color_discrete_map,
    animation_frame='Economic Freedom Score',
    hover_name='Country',
    # Hide certain animation + legendgroup from tooltop
    hover_data={
        'Economic Freedom Score': False,
        'LegendGroup': False,
        'The job market': ':.1f',
        'My job': ':.1f'
    },
    category_orders={
        'LegendGroup': ['Low (45-55)', 'Mid-low (55-65)', 'Mid-high (65-75)', 'High (75-85)', 'Global'],
        'Economic Freedom Score': bin_list
    },
    labels={
        'The job market': '% Expecting AI Improvement - The Job Market',
        'My job': "% Expecting AI Improvement - Respondants' Specific Job",
        'LegendGroup': 'Group:'
    }
)

# formatting
fig.update_xaxes(range=[0, 70])
fig.update_yaxes(range=[0, 70])
fig.update_traces(marker=dict(size=14, line=dict(width=1, color='DarkSlateGrey')))

# Global = black diamond in base traces
fig.update_traces(
    marker=dict(size=18, color='black', symbol='diamond'),
    selector=dict(legendgroup='Global')
)

# apply diamond to every animation frame
for frame in fig.frames:
    for trace in frame.data:
        if trace.legendgroup == 'Global':
            trace.update(marker=dict(size=18, color='black', symbol='diamond'))

# informative textbox bottom right
fig.add_annotation(
    text=(
        "<b>Economic Freedom Score</b> measures how market-oriented<br>"
        "a country's economy is using factors such as property rights,<br>"
        "business regulation, trade openness, and government<br>"
        "involvement in the economy.<br><br>"
        "<b>Higher scores</b> generally indicate economies with stronger<br>"
        "private enterprise and more open markets.<br>"
        "<b>Lower scores</b> generally indicate greater government control<br>"
        "or state direction of economic activity."
    ),
    xref='paper', yref='paper',
    x=1.15, y=0.15,
    xanchor='right', yanchor='bottom',
    showarrow=False,
    font=dict(size=10, color='#333333'),
    bgcolor='rgba(255, 255, 255, 0.85)',
    bordercolor='#AAAAAA',
    borderwidth=1,
    borderpad=8,
    align='left'
)

# ensure all title colors are black
fig.update_layout(
    title=dict(
        text="AI Optimism: Respondant's Job vs. The Job Market<br>Filtered by Economic Freedom Score",
        x=0.5,
        xanchor='center',
        font=dict(color='black')     
    ),
    xaxis=dict(
        title=dict(
            text='% Expecting AI Improvement - The Job Market',
            font=dict(color='black') 
        )
    ),
    yaxis=dict(
        title=dict(
            text="% Expecting AI Improvement - Respondants' Specific Job",
            font=dict(color='black')  
        )
    ),
    legend_title='Group:',
    height=680,
    width=950,
    template='plotly_white',
    legend=dict(
        bordercolor='#AAAAAA',
        borderwidth=1,
        bgcolor='rgba(255, 255, 255, 0.85)',
        font=dict(color='black'),
        title=dict(
            text='Group:',
            font=dict(color='black')
        )
))

fig.show()

fig.write_html('ai_optimism_scatterplot.html')
fig.write_image('ai_optimism_scatterplot.png')